const {Router}=require('express')
const user = require('../Controllers/postUser')
const login = require('../Controllers/Login')
const getData = require('../Controllers/get')
const getUser = require('../Controllers/getUser')
const authenticateUser = require('../Controllers/authenticate')
const postd = require('../Controllers/post')
const deleted = require('../Controllers/delete')
const update = require('../Controllers/update')
const logout = require('../Controllers/LogOut')
const router=Router()
module.exports=router
router.route('/post').post(user)
router.route('/login').post(login)
router.route('/getdata').get(authenticateUser,getData)
router.route('/data').post(authenticateUser,postd)
router.route('/getuser').get(getUser)
router.route('/delete/:id').delete(authenticateUser,deleted)
router.route('/update/:id').put(authenticateUser,update)
router.route('/logout').get(authenticateUser,logout)